# Generated by Django 2.1 on 2018-08-28 00:42

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('cpf', models.IntegerField(default=0)),
                ('celular', models.IntegerField(default=0)),
                ('dataNascimento', models.DateField()),
                ('batismo', models.BooleanField()),
                ('escolaridade', models.IntegerField(default=0)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
