# Generated by Django 2.1 on 2018-08-28 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_estudantes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudantes',
            new_name='Estudante',
        ),
    ]
