# Generated by Django 2.1 on 2018-08-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_auto_20180828_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='nome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
