# Generated by Django 2.1 on 2018-08-31 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0004_estudante_nome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
