# Generated by Django 2.1 on 2018-08-31 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0006_escolaridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='escolaridade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloworld.Escolaridade'),
        ),
    ]
