# Generated by Django 2.1 on 2018-09-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0012_cursoperiodoestudante'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='diaAniversario',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estudante',
            name='mesAniversario',
            field=models.IntegerField(default=0),
        ),
    ]
