# Generated by Django 2.1 on 2018-09-06 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0013_auto_20180906_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudante',
            name='dataNascimento',
        ),
    ]
