# Generated by Django 2.1 on 2018-09-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0014_remove_estudante_datanascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesdoAno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroMes', models.IntegerField()),
                ('nomeMes', models.CharField(max_length=255)),
            ],
        ),
    ]
