# Generated by Django 2.1 on 2018-09-07 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0015_mesdoano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='mesAniversario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloworld.MesdoAno'),
        ),
    ]
