# Generated by Django 2.1 on 2018-10-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0020_cursoperiodo_matriculasabertas'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='profissao',
            field=models.CharField(default='Não informado', max_length=255),
        ),
    ]
