# Generated by Django 2.1.2 on 2018-11-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0022_cursoperiodoestudantefinanceiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoperiodoestudante',
            name='pagamento',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
