# Generated by Django 2.1.2 on 2018-11-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0023_cursoperiodoestudante_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoperiodoestudante',
            name='pagamento',
            field=models.IntegerField(default=0, max_length=255),
        ),
    ]
